### ISSUE TITLE
[FEATURE] Ability to select the default concrete type of an abstract class 

### ISSUE THREAD

**Issue by thewhitewayofdelight** [mackysoft/Unity-SerializeReferenceExtensions#34]
## Description
Hi, thank you for this very useful package!

I have a suggestion to make the package more convenient to use, by being able to select the default concrete type of an abstract class rather than `<null>` like the image below (ex: default to DebugCommand). Is that possible? Or is it too complicated and not worth the time.
![image](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/87333145/f1736044-187d-4dae-80e5-e1a9dd8f8a72)

Thanks for your attention

**Comment by mackysoft** [comment]
Hi.

Sorry, the functionality of this library is implemented by an editor extension in `CustomPropertyDrawer` for Attribute, but it is not possible to implement this functionality because it is difficult to observe the array strictly by `PropertyDrawer`.

If such functionality is necessary, it would be necessary to observe changes in the length of the array in your component inspector editor extension.

I hope this is helpful !
