### ISSUE TITLE
[FEATURE]  How to use it with an EditorWindow?

### ISSUE THREAD

**Issue by whynames** [mackysoft/Unity-SerializeReferenceExtensions#44]
### Feature destription

Use it with an EditorWindow?

**Comment by mackysoft** [comment]
Hi.

Since `SubclassSelector` is a feature using `CustomPropertyDrawer`, it can be drawn using the `PropertyField` method of `EditorGUI` or `EditorGUILayout`, just like standard property drawing.

When drawing in the `EditorWindow`, you can create a `SerializedObject` from the target Unity object, find the target property with `FindProperty`, and draw it with `PropertyField`.
https://docs.unity3d.com/ScriptReference/SerializedObject.html

**Comment by adriengivry** [comment]
Hi!

Seems like when using `PropertyField` in a custom editor, the property doesn't get updated properly in the inspector until you close and re-open the inspector.

**MVP:**
```csharp
public class MyObject : ScriptableObject
{
    public ICommand command;
}

[CustomEditor(typeof(MyObject))]
public class MyCustomEditor : Editor
{
    public override void OnInspectorGUI()
    {
        var property = serializedObject.FindProperty("command");
        EditorGUILayout.PropertyField(property);
        serializedObject.ApplyModifiedProperties();
    }
}
```

**Example:**
![property-field-not-updated](https://github.com/mackysoft/Unity-SerializeReferenceExtensions/assets/33324216/196f9e9a-08c5-4c45-b3d5-c7db478e3fab)
