### ISSUE TITLE
[BUG] Fields with `[SubClassSelector]` become null

### ISSUE THREAD

**Issue by Antoshidza** [mackysoft/Unity-SerializeReferenceExtensions#71]
### What happened?

Fields with `[SubClassSelector]` become null each time after compile (no matter opened or not in inspector) with error in console:
`Release of invalid GC handle. The handle is from a previous domain. The release operation is skipped.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

The most weird thing is that data in asset file stays the same but field is actually null because NullReferenceException throwed if trying to access such field, and also when reassign thing back manually they doesn't duplicated in file like I create fresh asset.

I suspect that this package forces assets to be saved. If so then it is better to turn it off and let users just save assets as usual through File -> SaveProject. If I'm wrong then excuse me for wrong suggestion. Also it happens only with particular assets, Recreating asset fixes the problem.

### Package Version

1.4.0

### Unity Version

6000.0.23f1

**Comment by mackysoft** [comment]
@Antoshidza 
I am currently trying to reproduce the problem with Unity 6000, but it does not seem to work.

In this package, in the SubclassSelectorDrawer or ManagedRefernceContextualPropertyMenu, the SerializedObject.ApplyModifiedProperties() function is called to save asset changes but no further operations are performed, so I think that the asset may be broken due to some other phenomenon.

If you share more details about the situation, I may be able to help.

**Comment by Antoshidza** [comment]
Unfortunately I can't detect what cause asset to be broken, so if I will have any information I can reopen this issue or create a new one with reference to this and for now, I think we can close the issue. Just in case to know of such a problem.

**Comment by mackysoft** [comment]
Understood. Contact me if you need me.
